### ISSUE TITLE
Born again R module

### ISSUE THREAD

**Issue by bobaekang** [ICJIA/r-user-group#33]
## Summary

[Use R modules _natively_](https://github.com/bobaekang/r-module). (An upgrade from #10)

## Main

Recently I revisited a trick for using modules in R, which I [first introduced a while ago](#10). After trying it out in my own projects, I realized that there is a even better way to implement modules in R. This new approach still relies only on built-in language features but does away with the IIFE (immediately-invoked function expression) hack.

So I created [a new GitHub repository](https://github.com/bobaekang/r-module) for an upgraded approach to R modules, which includes an in-depth explanation, detailed examples, and a helper function `import_module()`.

Please feel free to check it out and share your thoughts!

**Comment by kgruschow** [comment]
I am just bumping this up in people’s in-boxes  as being an elegant way of handling the very common use case of data pre-processing, at it results in an object you can organize how you want.

So instead of having your file littered with LGBTQ_raw_SPSS and LGBTQ_recoded and LGBTQ_crosstab_ageXgender, you can have

LGBTQ$raw, LGBTQ$recoded, LGBTQ$ageXgender etc.

This has much larger impact than you would think because of autocompletion.

Highly recommend it
