### ISSUE TITLE
Module for storing views of data

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/r-user-group#36]
this is interesting concept that I have halfway functional.

The basic concept is a module that stores raw data as well as a series of ‘views’ of that data. The benefit being to essentially preprogram a series of subsets/recodes into the module for convenience, without making the module object balloon in size. The views would be 'lazily' interpreted. 

I have this mostly working, except to use it, the syntax ends up being short, simple, and horribly ugly.

For example:
`# module

raw <- data.table(read_sav(spssfile.sav))

List(
rawdata = raw,
view = function(){raw[,3:4]}
)   #view returns 3rd and 4th column of the rawdata`

from testing, 'module$view()' returns the desired data.table and 'module$view()[,1]' also works as subsetting that data.table. However having the (), while logically necessary because it’s technically a function, is syntactically very confusing.

Any idea how to make it so that module$view[,1] would work?

**Comment by bobaekang** [comment]
Thank you, @kgruschow, for sharing your use of [R module](#33)!

As to your question, I believe that there is no reason not to make your `module$view` to store an object instead of a function. In code,

```r
# module.R
raw <- data.table(read_sav(spssfile.sav))

List(
  rawdata = raw,
  view = raw[, 3:4]
)
```

This way, you should be able to access the subsetted `data.table` using `module$view` just as you would access the original table with `module$rawdata`.

Please give it a try and let me know this solves your problem 😃

**Comment by kgruschow** [comment]
I should clarify, that that works and was step 1, i already tried it before posting. The difference is lazy execution/keep the object's size small. 
My understanding is that "view = raw[3,4]"  creates a new data.table in the list. 
The function however, is only evaluated when called, so effectively lazy execution.

**Comment by bobaekang** [comment]
@kgruschow, thank you for the clarification.

I see why you'd prefer a functional call here. However, I think we need to think about the use case for the subsetted table. If all scripts importing the module eventually consume `view`, then I think there is no merit in making `view` a function call.

The next consideration would be: if the script that consumes `module$view` is calling it multiple times, then it might be worth simply assigning the return value of `module$view` to an object in that script. For example:

```r
view <- module$view()
view[1, ]
view[2, ]
# ... and so on
```

More fundamentally, when you dig deeper into how R copies objects in memory, you will find that R does _not_ create a copy simply because it is assigned (bound) to a new symbol--a new copy is created only when the object is modified. This behavior is often call as copy-on-write or copy-on-modify and, in fact, is what lazy evaluation means for R.

Since a `data.table` is at its core a list of vectors (columns), simply accessing then should not be considered a modification. That is to say, R should not create a copy of `raw[, 3:4]` as long as it is not modified.

Here are some reference materials on R's lazy evaluation:

* https://stackoverflow.com/questions/14884343/lazy-evaluation-in-r-is-assign-affected
* https://stackoverflow.com/questions/15759117/what-exactly-is-copy-on-modify-semantics-in-r-and-where-is-the-canonical-source
* https://cran.r-project.org/doc/manuals/r-patched/R-ints.html#Rest-of-header

**Comment by bobaekang** [comment]
Some points from in-person discussion between me and @kgruschow :

* What RStudio IDE's environment panel reports as object size can be misleading. Apparently, it simply adds up size of the object for all pointers (variables/fields in a list/columns in data.frame, etc.) instead of considering if multiple pointers are pointing to the same object in the memory.
* R is a garbage-collected language, which means that *deleting* a variable may not immediately free up the memory space the underlying object. This, also, can lead to some misunderstanding of the memory use at any given moment. 
* The aggregated size of all variables in the global environment does not give us an accurate picture of what the memory usage would be while running some operations on them. Certain operations would be creating temporary objects as part of the algorithms they implement, which do not show up in the global environment. And R being garbage-collected language, we as users cannot know in advance when the R will released memories for those temporary objects.
* Lazy evaluation is one of the basic feature of R--however, using a different distribution, such as [Microsoft R Open](https://mran.microsoft.com/open), may lead to different behaviors, which can be difficult to check or verify.

**Comment by kgruschow** [comment]
thanks Bobae, i went forward with basically the 1.0 sans functions and it seems to work fine thus far.

possibly separate than the first issue, but i think on topic: could we open up the github to push requests/file upload? I actually think it would be great to have shared modules available.

I have a very simple Unified Crime Reporting for DV module built and working, as well as a holidays with a useful convenience function, and am moving my census code into a new module now.

The method of using modules is good for organizing one's one code, and possibly better than good for sharing bundles of R code within a group like this, especially related to datasets more than one team is likely to use.

**Comment by bobaekang** [comment]
@kgruschow, that sounds like a great idea! Frankly, creating a repository of shared R code was definitely one of the original intentions I had for this GitHub repo for the User Group. I didn't have the module idea back then, but it now seems to be a perfect unit for the shared code.

That said, what do you think about bringing this up in the January meeting and discuss it with everyone? Plus, I'd really appreciate if you can open a new Issue and explain your intention. Better to have a new thread for that discussion than keeping it buried under other comments in the current thread--that is, in my opinion. 😃

**Comment by kgruschow** [comment]
@bobaekang my preference would be have write access, upload them, then have a new 'issue' that simply announcing their existence/asking for feature requests. worst case they sit idle, which is barely a change from existing state?
