### ISSUE TITLE
useful SQL tricks

### ISSUE THREAD

**Issue by kgruschow** [ICJIA/r-user-group#43]
Hi,

I recently discovered two methods to assist with running SQL code from within R, that make R considerably more pleasant when handling SQL:

1. You can store credentials using the keyring package, so that your connection "just works" from R securely.

```R
library(keyring) #used to store/retrieve keys like passwords for SQL
library(odbc) #database connections 1
library(DBI) #database connections 2

# run once to store password securely: keyring::key_set(InfoNet, username = KgruschowSQL)

InfoNet <- dbConnect(odbc::odbc(), 
                     "InfoNet",
                     uid=keyring::key_list("InfoNet")[1,2],
                     pwd=keyring::key_get("InfoNet", "KgruschowSQL"))
```

2. method to execute .sql file from project directory. This is a convenience function, but very convenient if you want to stay within R (and write .R and .SQL)

```R
library(readtext)
library(data.table)

Declarations <-"
Declare @Demo as varchar(120)='you can conveniently control external queries this way' "

run_ext_sql <- function(filename.sql){
  data.table(dbGetQuery(InfoNet,paste0(Declarations,"
                                       ",readtext(filename.sql, verbosity = 0))))
  }

sql_output <- run_ext_sql("local sql file.sql")
```

**Comment by bobaekang** [comment]
Thank you @kgruschow for sharing the tips! To other readers, here are some related resources you might want to check out:

* ["Securing Credentials"](https://db.rstudio.com/best-practices/managing-credentials/) page on _Database using R_ by RStudio
  * Describes how to set up the `keyring` package as well as other methods to securely provide authentication inputs when connecting to a database
* ["Run Queries Safely"](https://db.rstudio.com/best-practices/run-queries-safely/) page on _Database using R_ by RStudio
  * Gives examples of using `DBI:dbGetQuery` function for getting query results from a database connection. You can, in fact, provide the SQL text directly to the function instead of reading it from a file on disk.

By the way, if you don't want to add more dependencies (i.e. avoid yet another package, which, in this case, `readtext`), you can replace `readtext::readtext` with `readr::read_file`. `readr` is part of `tidyverse` packages, which means you are likely to have it installed already.

**Comment by kgruschow** [comment]
Thanks!

I actually started with direct SQL in my R code, and found that with a few convenience functions like this, there are considerable advantages to not doing that.

Specifically, if you have the SQL external, then RStudio provides syntax highlighting and auto-completion, as well as "Preview". This makes Rstudio pretty good at editing/updating simple SQL queries... so long as they are not inside an R file.

(you may even notice, I do include SQL in my R file, and then append it before the external file, in this case it allows "passing values" into the SQL. I will eventually make this so that the values are in R first, then the text, but not a high priority)

("readr: Read Rectangular Text Data" was misleading, turns out read_file works quite slightly faster (.4ms) and requires fewer arguments.  thanks!)
